# 1. Usar una versión de Python oficial y ligera
FROM python:3.10-slim

# 2. Configurar la carpeta de trabajo dentro del contenedor
WORKDIR /app

# 3. Copiar solo el archivo de requerimientos primero (optimiza tiempos de carga)
COPY requirements.txt .

# 4. Instalar las librerías
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copiar todo el resto de tu código al contenedor
COPY . .

# 6. El comando que se ejecutará al encender el contenedor
CMD ["python", "run_pipeline.py"]


